apiVersion: v1
kind: Pod
metadata:
  name: leonnginx
  labels: 
    app: nginx
spec:
  containers:
  - image: nginx
    name: leonnginx
    env:
    - name: LEONVAR
      value: pies
    ports:
    - containerPort: 80