apiVersion: apps/v1
kind: Deployment
metadata:
  name: pieswebqa
  labels:
    app: piesweb
    env: qa
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: piesweb
      env: qa
  template:
    metadata:
      labels:
        app: piesweb
        env: qa
    spec:
      containers:
      - name: piesweb
        image: baggypants12000/piesweb:latest
        ports:
        - containerPort: 80