apiVersion: apps/v1
kind: Deployment
metadata:
  name: piesweb
  labels:
    app: piesweb
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      app: piesweb
  template:
    metadata:
      labels:
        app: piesweb
    spec:
      containers:
      - name: piesweb
        image: baggypants12000/piesweb:latest
        ports:
        - containerPort: 80