# playbook (2 space indent)
# keywords: hosts, tasks, name, become
- hosts: userconfig
  name: Install nginx on all hosts
  become: true
  tasks: # this is the list of tasks to perform
  - name: "Ping" 
    ping:
  - name: "Install the nginx package"
    apt: # this is the module performing the tasks
      state: latest  # This is one of the arguments to the task
      name: nginx
      update_cache: true
# Play 2 LB


- name: Install the nginx loadbalancer config
  hosts: loadbalancers
  become: true
  vars:
    serverip1: "172.31.44.90"  # these vars are used in the nginx.conf.j2 file
    serverip2: "172.31.34.207"
  tasks:
  - name: copy the config file over
    template:
      dest: /etc/nginx/nginx.conf
      src: nginx-lb.conf.j2
    register: templatetaskoutput
    notify: 
    - restart-nginx
  - name: debug messages
    debug: 
      var: serverip1
  - name: Nice message
    debug:
      msg: "Hello, nice to see you, have a great deployment"
  - name: print the template task info
    debug:
      var: templatetaskoutput.size
  handlers:
  - name: restart-nginx
    systemd:
      name: nginx
      state: restarted
    
- name: install the webpages
  become: true
  hosts: appservers
  tasks:
  - name: copy the web page
    copy:
      src: example-webpage.html
      dest: /var/www/html/index.nginx-debian.html