# playbook (2 space indent)
# keywords: hosts, tasks, name, become
- hosts: userconfig
  name: Install nginx on all hosts
  become: true
  tasks: # this is the list of tasks to perform
  - name: "Ping" 
    ping:
  - name: "Install the nginx package"
    apt: # this is the module performing the tasks
      state: latest  # This is one of the arguments to the task
      name: nginx
      update_cache: true
   

- name: Install the nginx loadbalancer config
  hosts: loadbalancers
  become: true
  tasks:
  - name: copy ythe config file over
    copy:
      dest: /etc/nginx/nginx.conf 
      src: nginx-lb.conf
  - name:
    systemd:
      name: nginx
      state: restarted
    
- name: install the webpages
  become: true
  hosts: appservers
  tasks:
  - name: copy the web page
    copy:
      src: example-webpage.html
      dest: /var/www/html/index.nginx-debian.html