all:
  hosts:
    172.31.34.249:
    172.31.32.236:
  children:
    groupnamea:
      vars:
        variables_set_for_the_whole_group: var_value
      hosts:
        host1:
        host2:
    groupnameb:
      hosts:
        host3:
          variable_for_an_individual_host: var_value
        host4:
    loadbalancers:
      hosts:
    appservers:
      hosts:
    userconfig:
      hosts:
        172.31.36.199:
        172.31.44.90:
        172.31.34.207:
          datavar: "puddings"
    dockerhost:
      hosts:
        
