- name: This playbook will deploy a thing
  hosts: userconfig
  become: true
  tasks:
  - name: make some diretcory
    file:
      path: "/etc/{{ datavar }}.d"
      state: directory
  - name: copy some file somewhere
    copy: 
      content: "{{ datavar}} Some Random String In"
      dest: /etc/{{ datavar }}.d/{{ datavar }}.conf
  - name: touch a file in the working directory
    vars: 
      taskvar: "wobble"
    file:
      path: "/etc/{{ datavar }}"
      state: touch
  - name: install good old nginx
    apt:
      name: nginx
      update_cache: true
      state: latest
  - name: Put the hostname in a webfile
    copy:
      content: "This server is: {{ ansible_fqdn }}"
      dest: /var/www/html/index.nginx-debian.html
  
  
